### PR TITLE
feat: use official Steam python client

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Do we need it tho? The client seems like a thin wrapper around the API, we're adding another dependency

**Comment by Alchez** [comment]
For the resolve URL, I don't mind keeping requests. But I'd rather use their own implementation to manage ID strings.

**Comment by vjFaLk** [comment]
We should replace `requests` with https://aiohttp.readthedocs.io/en/stable/index.html

This is already used within `discord.py` and is async

**Comment by Alchez** [comment]
> We should replace `requests` with [aiohttp.readthedocs.io/en/stable/index.html](https://aiohttp.readthedocs.io/en/stable/index.html)
> 
> This is already used within `discord.py` and is async

Ooh, shiny, I'll check it out

**Pull request merged**
